-- INNER JOIN
-- JOIN 방식 중 가장 흔히 사용되는 유형이다.
-- 이 방식은 두 테이블 간의 일치하는 데이터만을 기준으로
-- 결과를 포함시키기 때문에
-- 관련성 높은 데이터를 정확하게 추출하는 데 유용하다.
SELECT *
FROM VIEW_PLAYER_NAME;
--CREATE VIEW VIEW_PLAYER_NAME AS 
SELECT PLAYER_NAME, TEAM_ID 
FROM PLAYER;

SELECT *
FROM VIEW_TEAM_NAME;
--CREATE VIEW VIEW_TEAM_NAME AS
--SELECT TEAM_ID, TEAM_NAME
--FROM TEAM t; 

-- 위에서 만든 VIEW테이블 두 개를
-- INNER JOIN으로 병합해보자.
--CREATE VIEW VIEW_PLAYER_TEAM_NAME AS
SELECT PN.PLAYER_NAME 선수명, 
PN.TEAM_ID 선수번호, TN.TEAM_NAME 팀명
FROM VIEW_PLAYER_NAME PN
INNER JOIN VIEW_TEAM_NAME TN
ON PN.TEAM_ID = TN.TEAM_ID;

SELECT *
FROM VIEW_PLAYER_TEAM_NAME;

